2017-10-18 20:59:38 WARNING (MainThread) [homeassistant.setup] Setup of sensor is taking over 10 seconds.
2017-10-18 21:36:30 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) unable to open database file
2017-10-18 21:36:30 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) unable to open database file. (retrying in 3 seconds)
2017-10-18 21:36:33 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) unable to open database file
2017-10-18 21:36:33 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) unable to open database file. (retrying in 3 seconds)
2017-10-18 21:36:36 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"old_state": {"last_updated": "2017-10-18T23:35:30.752368+00:00", "entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_setting": " ... (746 characters truncated) ... 02, "next_rising": "2017-10-19T08:20:46+00:00", "friendly_name": "Sun"}, "last_changed": "2017-10-18T22:59:28.120810+00:00"}, "entity_id": "sun.sun"}', 'LOCAL', '2017-10-18 23:36:30.752091', '2017-10-18 23:36:36.827357')]
2017-10-18 21:36:36 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"old_state": {"last_updated": "2017-10-18T23:35:30.752368+00:00", "entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_setting": " ... (746 characters truncated) ... 02, "next_rising": "2017-10-19T08:20:46+00:00", "friendly_name": "Sun"}, "last_changed": "2017-10-18T22:59:28.120810+00:00"}, "entity_id": "sun.sun"}', 'LOCAL', '2017-10-18 23:36:30.752091', '2017-10-18 23:36:36.827357')]. (retrying in 3 seconds)
2017-10-18 21:36:39 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_setting": "2017-10-19T20:59:21+00:00", "next_noon": "2017-10-19T14:40:03+00:00", "azimuth": 239.55, "next_midnight": "2017-10-19T02:39:57+00:0 ... (27 characters truncated) ... 9T21:22:02+00:00", "next_dawn": "2017-10-19T07:58:05+00:00", "elevation": -35.02, "next_rising": "2017-10-19T08:20:46+00:00", "friendly_name": "Sun"}', None, '2017-10-18 22:59:28.120810', '2017-10-18 23:36:30.751927', '2017-10-18 23:36:39.855858')]
2017-10-18 21:36:39 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_setting": "2017-10-19T20:59:21+00:00", "next_noon": "2017-10-19T14:40:03+00:00", "azimuth": 239.55, "next_midnight": "2017-10-19T02:39:57+00:0 ... (27 characters truncated) ... 9T21:22:02+00:00", "next_dawn": "2017-10-19T07:58:05+00:00", "elevation": -35.02, "next_rising": "2017-10-19T08:20:46+00:00", "friendly_name": "Sun"}', None, '2017-10-18 22:59:28.120810', '2017-10-18 23:36:30.751927', '2017-10-18 23:36:39.855858')]. (retrying in 3 seconds)
2017-10-18 21:36:42 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"old_state": {"last_updated": "2017-10-18T23:35:30.752368+00:00", "entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_setting": " ... (746 characters truncated) ... 02, "next_rising": "2017-10-19T08:20:46+00:00", "friendly_name": "Sun"}, "last_changed": "2017-10-18T22:59:28.120810+00:00"}, "entity_id": "sun.sun"}', 'LOCAL', '2017-10-18 23:36:30.752091', '2017-10-18 23:36:42.883037')]
2017-10-18 21:36:42 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"old_state": {"last_updated": "2017-10-18T23:35:30.752368+00:00", "entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_setting": " ... (746 characters truncated) ... 02, "next_rising": "2017-10-19T08:20:46+00:00", "friendly_name": "Sun"}, "last_changed": "2017-10-18T22:59:28.120810+00:00"}, "entity_id": "sun.sun"}', 'LOCAL', '2017-10-18 23:36:30.752091', '2017-10-18 23:36:42.883037')]. (retrying in 3 seconds)
2017-10-18 21:36:45 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_setting": "2017-10-19T20:59:21+00:00", "next_noon": "2017-10-19T14:40:03+00:00", "azimuth": 239.55, "next_midnight": "2017-10-19T02:39:57+00:0 ... (27 characters truncated) ... 9T21:22:02+00:00", "next_dawn": "2017-10-19T07:58:05+00:00", "elevation": -35.02, "next_rising": "2017-10-19T08:20:46+00:00", "friendly_name": "Sun"}', None, '2017-10-18 22:59:28.120810', '2017-10-18 23:36:30.751927', '2017-10-18 23:36:45.913834')]
2017-10-18 21:36:45 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_setting": "2017-10-19T20:59:21+00:00", "next_noon": "2017-10-19T14:40:03+00:00", "azimuth": 239.55, "next_midnight": "2017-10-19T02:39:57+00:0 ... (27 characters truncated) ... 9T21:22:02+00:00", "next_dawn": "2017-10-19T07:58:05+00:00", "elevation": -35.02, "next_rising": "2017-10-19T08:20:46+00:00", "friendly_name": "Sun"}', None, '2017-10-18 22:59:28.120810', '2017-10-18 23:36:30.751927', '2017-10-18 23:36:45.913834')]. (retrying in 3 seconds)
2017-10-18 21:36:48 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"old_state": {"last_updated": "2017-10-18T23:35:30.752368+00:00", "entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_setting": " ... (746 characters truncated) ... 02, "next_rising": "2017-10-19T08:20:46+00:00", "friendly_name": "Sun"}, "last_changed": "2017-10-18T22:59:28.120810+00:00"}, "entity_id": "sun.sun"}', 'LOCAL', '2017-10-18 23:36:30.752091', '2017-10-18 23:36:48.941882')]
2017-10-18 21:36:48 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"old_state": {"last_updated": "2017-10-18T23:35:30.752368+00:00", "entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_setting": " ... (746 characters truncated) ... 02, "next_rising": "2017-10-19T08:20:46+00:00", "friendly_name": "Sun"}, "last_changed": "2017-10-18T22:59:28.120810+00:00"}, "entity_id": "sun.sun"}', 'LOCAL', '2017-10-18 23:36:30.752091', '2017-10-18 23:36:48.941882')]. (retrying in 3 seconds)
2017-10-18 21:36:51 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"old_state": {"last_updated": "2017-10-18T23:35:30.752368+00:00", "entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_setting": " ... (746 characters truncated) ... 02, "next_rising": "2017-10-19T08:20:46+00:00", "friendly_name": "Sun"}, "last_changed": "2017-10-18T22:59:28.120810+00:00"}, "entity_id": "sun.sun"}', 'LOCAL', '2017-10-18 23:36:30.752091', '2017-10-18 23:36:51.970128')]
2017-10-18 21:36:51 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('state_changed', '{"old_state": {"last_updated": "2017-10-18T23:35:30.752368+00:00", "entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_setting": " ... (746 characters truncated) ... 02, "next_rising": "2017-10-19T08:20:46+00:00", "friendly_name": "Sun"}, "last_changed": "2017-10-18T22:59:28.120810+00:00"}, "entity_id": "sun.sun"}', 'LOCAL', '2017-10-18 23:36:30.752091', '2017-10-18 23:36:51.970128')]. (retrying in 3 seconds)
2017-10-18 21:36:55 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_setting": "2017-10-19T20:59:21+00:00", "next_noon": "2017-10-19T14:40:03+00:00", "azimuth": 239.55, "next_midnight": "2017-10-19T02:39:57+00:0 ... (27 characters truncated) ... 9T21:22:02+00:00", "next_dawn": "2017-10-19T07:58:05+00:00", "elevation": -35.02, "next_rising": "2017-10-19T08:20:46+00:00", "friendly_name": "Sun"}', None, '2017-10-18 22:59:28.120810', '2017-10-18 23:36:30.751927', '2017-10-18 23:36:54.998021')]
2017-10-18 21:36:55 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_setting": "2017-10-19T20:59:21+00:00", "next_noon": "2017-10-19T14:40:03+00:00", "azimuth": 239.55, "next_midnight": "2017-10-19T02:39:57+00:0 ... (27 characters truncated) ... 9T21:22:02+00:00", "next_dawn": "2017-10-19T07:58:05+00:00", "elevation": -35.02, "next_rising": "2017-10-19T08:20:46+00:00", "friendly_name": "Sun"}', None, '2017-10-18 22:59:28.120810', '2017-10-18 23:36:30.751927', '2017-10-18 23:36:54.998021')]. (retrying in 3 seconds)
2017-10-18 21:36:58 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_setting": "2017-10-19T20:59:21+00:00", "next_noon": "2017-10-19T14:40:03+00:00", "azimuth": 239.55, "next_midnight": "2017-10-19T02:39:57+00:0 ... (27 characters truncated) ... 9T21:22:02+00:00", "next_dawn": "2017-10-19T07:58:05+00:00", "elevation": -35.02, "next_rising": "2017-10-19T08:20:46+00:00", "friendly_name": "Sun"}', None, '2017-10-18 22:59:28.120810', '2017-10-18 23:36:30.751927', '2017-10-18 23:36:58.029652')]
2017-10-18 21:36:58 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: states [SQL: 'INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('sun', 'sun.sun', 'below_horizon', '{"next_setting": "2017-10-19T20:59:21+00:00", "next_noon": "2017-10-19T14:40:03+00:00", "azimuth": 239.55, "next_midnight": "2017-10-19T02:39:57+00:0 ... (27 characters truncated) ... 9T21:22:02+00:00", "next_dawn": "2017-10-19T07:58:05+00:00", "elevation": -35.02, "next_rising": "2017-10-19T08:20:46+00:00", "friendly_name": "Sun"}', None, '2017-10-18 22:59:28.120810', '2017-10-18 23:36:30.751927', '2017-10-18 23:36:58.029652')]. (retrying in 3 seconds)
2017-10-18 21:36:58 ERROR (Recorder) [homeassistant.components.recorder] Error in database update. Could not save after 11 tries. Giving up
2017-10-18 21:37:17 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('homeassistant_stop', '{}', 'LOCAL', '2017-10-18 23:37:17.240767', '2017-10-18 23:37:17.260290')]
2017-10-18 21:37:17 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('homeassistant_stop', '{}', 'LOCAL', '2017-10-18 23:37:17.240767', '2017-10-18 23:37:17.260290')]. (retrying in 3 seconds)
2017-10-18 21:37:20 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('homeassistant_stop', '{}', 'LOCAL', '2017-10-18 23:37:17.240767', '2017-10-18 23:37:20.291351')]
2017-10-18 21:37:20 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('homeassistant_stop', '{}', 'LOCAL', '2017-10-18 23:37:17.240767', '2017-10-18 23:37:20.291351')]. (retrying in 3 seconds)
2017-10-18 21:37:23 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('homeassistant_stop', '{}', 'LOCAL', '2017-10-18 23:37:17.240767', '2017-10-18 23:37:23.324342')]
2017-10-18 21:37:23 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('homeassistant_stop', '{}', 'LOCAL', '2017-10-18 23:37:17.240767', '2017-10-18 23:37:23.324342')]. (retrying in 3 seconds)
2017-10-18 21:37:26 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('homeassistant_stop', '{}', 'LOCAL', '2017-10-18 23:37:17.240767', '2017-10-18 23:37:26.350136')]
2017-10-18 21:37:26 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('homeassistant_stop', '{}', 'LOCAL', '2017-10-18 23:37:17.240767', '2017-10-18 23:37:26.350136')]. (retrying in 3 seconds)
2017-10-18 21:37:29 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('homeassistant_stop', '{}', 'LOCAL', '2017-10-18 23:37:17.240767', '2017-10-18 23:37:29.382292')]
2017-10-18 21:37:29 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('homeassistant_stop', '{}', 'LOCAL', '2017-10-18 23:37:17.240767', '2017-10-18 23:37:29.382292')]. (retrying in 3 seconds)
2017-10-18 21:37:32 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('homeassistant_stop', '{}', 'LOCAL', '2017-10-18 23:37:17.240767', '2017-10-18 23:37:32.412327')]
2017-10-18 21:37:32 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created) VALUES (?, ?, ?, ?, ?)'] [parameters: ('homeassistant_stop', '{}', 'LOCAL', '2017-10-18 23:37:17.240767', '2017-10-18 23:37:32.412327')]. (retrying in 3 seconds)
